nohup timeout 20h python main.py \
    --output_path data/wikipedia_synthetic.jsonl \
    --model Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled \
    --num_examples 50000 \
    --batch_size 16 \
    --tensor_parallel_size 2 \
    --max_tokens 4096 \
    --temperature 0.9 \
    --skip 0 \
    --seed 42 \
    --shuffle_buffer 50000 &> wikipedia_synthetic.log &