nohup timeout 20h python main.py \
    --output_path data/wikipedia_synthetic.jsonl \
    --model Jackrong/Qwopus3.6-27B-v1-preview-GGUF \
    --tokenizer Jackrong/Qwopus3.6-27B-v1-preview \
    --gguf_file Qwopus3.6-27B-v1-preview-Q4_K_M.gguf \
    --num_examples 64000 \
    --batch_size 32 \
    --tensor_parallel_size 2 \
    --max_tokens 3072 \
    --temperature 0.9 \
    --skip 0 \
    --seed 64 \
    --shuffle_buffer 50000 &> wikipedia_synthetic.log &