
# Each entry: (genre_name, brief_description_for_the_model)
TEXT_GENRES = [
    ("encyclopedia entry",       "A neutral, third-person encyclopedic paragraph as found in a reference work."),
    ("news article lede",        "The opening sentence(s) of a news article: who, what, when, where, why — direct and punchy."),
    ("empirical paper finding",  "A single key result or finding reported in a scientific paper: specific, data-grounded, past-tense."),
    ("humanities paper argument","A claim or interpretive assertion from a humanities essay: argumentative, citational, present-tense."),
    ("Reddit post",              "A casual first-person post on a topic-specific subreddit: conversational, opinionated, informal."),
    ("product or book review",   "A short consumer review: personal experience, evaluative tone, concrete details."),
    ("personal blog post",       "A reflective first-person blog entry: engaging, anecdotal, written for a general audience."),
    ("forum Q&A answer",         "A direct answer to a question in an online forum: practical, slightly informal, to the point."),
    ("documentary narration",    "Voice-over narration from a documentary: evocative, present-tense, cinematic pacing."),
    ("textbook explanation",     "A pedagogical passage explaining a concept to students: clear definitions, structured reasoning."),
    ("biography excerpt",        "A passage from a biography or profile: subject-focused, narrative, with specific life details."),
    ("travel guide entry",       "Descriptive travel-guide prose: vivid sensory detail, practical information, second-person warmth."),
    ("social media thread",      "The opening tweet or thread post: short, declarative, hook-driven, often with a strong claim."),
    ("legal or policy document", "Dry, precise prose from a regulation, contract, or policy brief: formal, hedged, impersonal."),
    ("how-it-works explainer",   "A plain-language explainer breaking down a process or mechanism for a curious lay reader."),
    ("letter or email",          "An excerpt from a formal or semi-formal letter: addressed tone, clear purpose, specific context."),
    ("op-ed / opinion column",   "A strong personal argument in a newspaper opinion piece: direct, polemical, first-person authority."),
    ("sports commentary",        "Live or post-match sports commentary: energetic, present/past-tense mix, statistics and drama."),
    ("obituary",                 "A respectful summary of a person's life and legacy: past-tense, commemorative, specific achievements."),
    ("press release",            "Corporate or institutional announcement: formal, promotional, third-person, structured facts."),
    ("oral history excerpt",     "A first-person spoken account from an interview or memoir: conversational, personal memory, vivid detail."),
    ("satirical piece",          "Dry or absurdist humor commenting on a real topic: deadpan, ironic, mimics a serious register."),
    ("customer complaint",       "A frustrated but specific complaint message: first-person, grievance-driven, concrete incident."),
    ("listicle entry",           "One item from a numbered or bulleted web list: punchy, self-contained, slightly informal."),
    ("diary or journal entry",   "An intimate personal note: introspective, present or past-tense, emotional, written for oneself."),
    ("tabloid headline or lede", "Sensational, breathless tabloid prose: punchy verbs, hyperbole, celebrity or scandal focus."),
    ("speech excerpt",           "A line from a formal speech or address: rhetorical, second-person appeal, elevated register."),
    ("instruction manual step",  "A single procedural step from a technical manual: imperative mood, precise, numbered-list style."),
    ("recipe",                   "A cooking recipe step or ingredient note: imperative or descriptive, precise quantities, sensory cues."),
    ("academic abstract",        "The abstract of a research paper: structured summary of aim, method, results, and conclusion."),
    ("children's book passage",  "Simple, rhythmic prose for young readers: short sentences, concrete imagery, gentle or playful tone."),
    ("medical patient leaflet",  "Plain-language health information for patients: reassuring, imperative warnings, structured sections."),
    ("advertisement copy",       "Promotional text for a product or service: benefit-driven, imperative or second-person, punchy hook."),
    ("crowdfunding pitch",       "A campaign pitch seeking public backing: emotive, first-person, problem–solution–ask structure."),
    ("job posting",              "A job advertisement: role-focused, bullet-pointed requirements, formal-yet-inviting register."),
    ("technical README",         "Developer-facing documentation: terse, imperative, code-adjacent, assumes technical literacy."),
    ("FAQ entry",                "A question-and-answer pair from a help or support page: direct, practical, second-person."),
    ("podcast transcript excerpt", "A lightly edited spoken-word passage: conversational rhythm, filler words, topic-driven."),
    ("court or legal testimony", "A first-person account given under oath: precise, chronological, hedged, formal diction."),
    ("financial report excerpt", "A passage from an annual report or earnings release: numerical, forward-looking statements, formal."),
    ("nature writing",           "Reflective prose about the natural world: sensory, slow-paced, ecological awareness."),
    ("self-help passage",        "Motivational advice prose: second-person coaching, actionable steps, optimistic framing."),
    ("political manifesto excerpt", "A programmatic statement of values and goals: declarative, urgent, ideologically charged."),
    ("museum or exhibit label",  "A short interpretive text beside an artifact or artwork: neutral, informative, present-tense."),
    ("investigative journalism", "A passage from a long-form investigative piece: evidence-driven, narrative tension, named sources."),
    ("fantasy or sci-fi world-building", "Descriptive prose establishing a fictional world's rules or setting: immersive, invented terminology."),
    ("chat or SMS exchange",     "An informal text-message conversation: fragmented sentences, abbreviations, real-time register."),
    ("grant proposal excerpt",   "Academic or NGO funding application prose: formal, objective-driven, evidence-cited, future-tense."),
    ("error message or system alert", "Terse software-generated notification: passive or imperative, code references, minimal prose."),
    ("weather forecast",         "Meteorological bulletin: technical terminology, probabilistic language, spatial and temporal precision."),
]